In [1]:
!pip install numpy

     ---------------------------------------- 0.0/60.9 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.9 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.9 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.9 kB ? eta -:--:--
     ------------- ------------------------- 20.5/60.9 kB 73.1 kB/s eta 0:00:01
     ------------- ------------------------- 20.5/60.9 kB 73.1 kB/s eta 0:00:01
     ------------------- ------------------ 30.7/60.9 kB 100.9 kB/s eta 0:00:01
     ------------------------- ------------ 41.0/60.9 kB 122.9 kB/s eta 0:00:01
     -------------------------------------- 60.9/60.9 kB 162.3 kB/s eta 0:00:00
   ---------------------------------------- 0.0/13.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/13.0 MB ? eta -:--:--
   ---------------------------------------- 0.1/13.0 MB 1.7 MB/s eta 0:00:08
    --------------------------------------- 0.3/13.0 MB 3.2 MB/s eta 0:00:04
   -- ---------


[notice] A new release of pip is available: 24.0 -> 25.1.1
[notice] To update, run: C:\Users\91868\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.1'

In [3]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [4]:
l = [1,2,3,4,5]

In [5]:
type(1)

int

In [6]:
type(arr)

numpy.ndarray

In [7]:
#list vs numpy

In [8]:
l = [1, 1.5,"Mohit"]

In [9]:
l

[1, 1.5, 'Mohit']

In [10]:
arr = np.array([1,1.5,12,34,'mohit'])
arr

array(['1', '1.5', '12', '34', 'mohit'], dtype='<U32')

In [11]:
arr.dtype

dtype('<U32')

In [12]:
arr.ndim

1

In [13]:
arr.size

5

In [14]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [15]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr = np.array